
defaults: &defaults
  redis.host : 192.168.211.246
  redis.port : 6379
  service.zookeeper.address : 192.168.211.231
  service.zookeeper.port : 2181
  service.interface.list :
    #- com.yougou.pc.api.ICommodityBaseApiService
    - com.yougou.cms.api.ICMSApi

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
